--- 
manifest:
  type: single
args:
  foldername: moonshot_debug
  expname: v3_n40_1e4_no_aug
  load_path: tempdata/chemformer/model.ckpt
  modelname: moonshot
  seed: 1337

  load_override:
    # model args
    module_only: True
    dim_model: 512
    dim_coords: [224, 224, 64]
    coord_enc: sce
    wavelength_bounds: [[0.01, 250], [0.01, 250]]
    gce_resolution: 0.1
    heads: 4
    layers: 4
    lr: 1.0e-4

  # control args
  actually_run: True
  force_start: True
  data_len: 40

  # trainer args
  epochs: 1000
  batch_size: 32

  # tb_args
  metric: val/mean_loss
  metricmode: min
  patience: 1000
  best_metrics: ["val/mean_loss"]
  best_metric_modes: ["min"]

  # data_args
  module_type: gim
  feats: [HSQC, SMILES]
  feats_handlers: [pad, tokenise]
  token_file: tempdata/chemformer/bart_vocab.txt
  ds_path: tempdata/SMILES_dataset
  num_workers: 4
  smiles_augment: False
