--- 
manifest:
  type: single
args: 
  foldername: debug
  expname: debug
  ranking_set_path: tempdata/SMILES_ranking_sets/val/rankingset.pt
  dim_model: 256
  dim_coords: 120,120,16
  coord_enc: gce
  gce_resolution: 0.1
  heads: 4
  layers: 4