--- 
manifest:
  type: single
args:
  foldername: debug
  expname: smart_clip_debug
  modelname: smart_clip
  seed: 1337

  # control args
  actually_run: True
  force_start: True
  data_len: 300

  # trainer args
  epochs: 25
  batch_size: 64

  # tb_args
  metric: val/mean_loss
  metricmode: min
  best_metrics: ["val/mean_loss"]
  best_metric_modes: ["min"]
  patience: 30
  
  # model args
  chemformer_path: "tempdata/chemformer/model.ckpt"
  projection_dim: 256
  lr: 1.0e-5
  coord_enc: sce
  enc_args: 
    wavelength_bounds: [[0.01, 150], [0.01, 150]]
  dim_model: 128

  # data_args
  module_type: gim
  feats: [HSQC, SMILES]
  feats_handlers: [pad_and_mask, tokenise_and_mask_encoder]
  token_file: tempdata/chemformer/bart_vocab.txt
  ds_path: tempdata/SMILES_dataset
  num_workers: 4
