--- 
manifest:
  type: single
args:
  foldername: debug
  expname: debug

  # control args
  actually_run: True
  force_start: True

  # trainer args
  epochs: 3

  # model args
  modelname: hsqc_transformer
  ranking_set_path: tempdata/SMILES_ranking_sets/val/rankingset.pt
  dim_model: 256
  dim_coords: [120, 120, 16]
  coord_enc: sce
  wavelength_bounds: [[0.01, 250], [0.01, 250]]
  gce_resolution: 0.1
  batch_size: 32
  heads: 4
  layers: 4

  # tb_args
  metric: val/mean_ce_loss
  metricmode: max
  patience: 30

  # data_args
  feats: [HSQC, R2-6144FP]
  feats_handlers: [pad, None]
  ds_path: tempdata/SMILES_dataset

