---
manifest:
  type: single
args:
  foldername: smart_clip
  expname: clip_1e_5
  modelname: smart_clip
  seed: 1337

  # control args
  actually_run: True
  force_start: True

  # trainer args
  epochs: 150
  batch_size: 48

  # tb_args
  metric: val/mean_loss
  metricmode: min
  patience: 30

  # model args
  chemformer_path: "tempdata/chemformer/model.ckpt"
  projection_dim: 256
  lr: 1.0e-5
  coord_enc: sce
  enc_args:
    wavelength_bounds: [[0.01, 150], [0.01, 150]]
  dim_coords: [60, 60, 8]
  dim_model: 128

  # data_args
  module_type: gim
  feats: [HSQC, SMILES]
  feats_handlers: [pad_and_mask, tokenise_and_mask_encoder]
  token_file: tempdata/chemformer/bart_vocab.txt
  ds_path: tempdata/SMILES_dataset
  num_workers: 12
